# Combined graph
experiment1 = read.csv("./Archivos_graficas/experiment1.csv")
pdf(file="./Archivos_graficas/experiment1-1.pdf",height=6,width=10) 
plot(experiment1$X...Features,experiment1$WDH,log="y",xlab="# Features", ylab="Resolution time (sec)",type="p",pch=19,col="lightblue3",cex=1) 
points(experiment1$X...Features,experiment1$BCH,col="lightblue4",pch=15) 
points(experiment1$X...Features, experiment1$SVIH,col="lightcoral",pch=16) 
points(experiment1$X...Features, experiment1$A20H,col="thistle4",pch=17) 
lines(experiment1$X...Features,experiment1$WDH,col="lightblue3",lty="twodash") 
lines(experiment1$X...Features,experiment1$BCH,col="lightblue4",lty="solid") 
lines(experiment1$X...Features, experiment1$SVIH,col="lightcoral",lty="dotted") 
lines(experiment1$X...Features, experiment1$A20H,col="thistle4",lty="longdash") 
legend("bottomright",c("WD", "CID", "Cross*C", "2OC"),lty=c(6,1,3,5), col=c("lightblue3", "lightblue4", "lightcoral",  "thistle4"))
dev.off()

# Independend graphs
experiment1_1FM = read.csv("./Archivos_graficas/experiment1-1FMs.csv")
experiment1_2FM = read.csv("./Archivos_graficas/experiment1-2FMs.csv")
experiment1_3FM = read.csv("./Archivos_graficas/experiment1-3FMs.csv")
experiment1_4FM = read.csv("./Archivos_graficas/experiment1-4FMs.csv")
experiment1_5FM = read.csv("./Archivos_graficas/experiment1-5FMs.csv")

pdf(file="./Archivos_graficas/experiment1-2.pdf",width=10,height=9.6,,cex=1) 
par(mfrow=c(3,2))

plot(experiment1_1FM$X...Features,experiment1_1FM$WD,log="y",xlab="2 FMs", ylab="Resolution time (sec)",type="p",pch=19,col="lightblue3") 
points(experiment1_1FM$X...Features,experiment1_1FM$CID,col="lightblue4",pch=15) 
points(experiment1_1FM$X...Features,experiment1_1FM$CrossC,col="lightcoral",pch=16) 
points(experiment1_1FM$X...Features,experiment1_1FM$OC,col="thistle4",pch=17) 
lines(experiment1_1FM$X...Features,experiment1_1FM$WD,col="lightblue3",lty="twodash") 
lines(experiment1_1FM$X...Features,experiment1_1FM$CID,col="lightblue4",lty="solid") 
lines(experiment1_1FM$X...Features,experiment1_1FM$CrossC,col="lightcoral",lty="dotted") 
lines(experiment1_1FM$X...Features,experiment1_1FM$OC,col="thistle4",lty="longdash") 
legend("topleft",c("WD", "CID", "Cross*C", "2OC"),lty=c(6,1,3,5), col=c("lightblue3", "lightblue4", "lightcoral",  "thistle4"))


plot(experiment1_2FM$X...Features,experiment1_2FM$WD,log="y",xlab="2 FMs", ylab="Resolution time (sec)",type="p",pch=19,col="lightblue3") 
points(experiment1_2FM$X...Features,experiment1_2FM$CID,col="lightblue4",pch=15) 
points(experiment1_2FM$X...Features,experiment1_2FM$CrossC,col="lightcoral",pch=16) 
points(experiment1_2FM$X...Features,experiment1_2FM$OC,col="thistle4",pch=17) 
lines(experiment1_2FM$X...Features,experiment1_2FM$WD,col="lightblue3",lty="twodash") 
lines(experiment1_2FM$X...Features,experiment1_2FM$CID,col="lightblue4",lty="solid") 
lines(experiment1_2FM$X...Features,experiment1_2FM$CrossC,col="lightcoral",lty="dotted") 
lines(experiment1_2FM$X...Features,experiment1_2FM$OC,col="thistle4",lty="longdash") 
legend("topleft",c("WD", "CID", "Cross*C", "2OC"),lty=c(6,1,3,5), col=c("lightblue3", "lightblue4", "lightcoral",  "thistle4"))

plot(experiment1_3FM$X...Features,experiment1_3FM$WD,log="y",xlab="3 FMs", ylab="Resolution time (sec)",type="p",pch=19,col="lightblue3") 
points(experiment1_3FM$X...Features,experiment1_3FM$CID,col="lightblue4",pch=15) 
points(experiment1_3FM$X...Features,experiment1_3FM$CrossC,col="lightcoral",pch=16) 
points(experiment1_3FM$X...Features,experiment1_3FM$OC,col="thistle4",pch=17) 
lines(experiment1_3FM$X...Features,experiment1_3FM$WD,col="lightblue3",lty="twodash") 
lines(experiment1_3FM$X...Features,experiment1_3FM$CID,col="lightblue4",lty="solid") 
lines(experiment1_3FM$X...Features,experiment1_3FM$CrossC,col="lightcoral",lty="dotted") 
lines(experiment1_3FM$X...Features,experiment1_3FM$OC,col="thistle4",lty="longdash") 
legend("topleft",c("WD", "CID", "Cross*C", "2OC"),lty=c(6,1,3,5), col=c("lightblue3", "lightblue4", "lightcoral",  "thistle4"))

plot(experiment1_4FM$X...Features,experiment1_4FM$WD,log="y",xlab="4 FMs", ylab="Resolution time (sec)",type="p",pch=19,col="lightblue3") 
points(experiment1_4FM$X...Features,experiment1_4FM$CID,col="lightblue4",pch=15) 
points(experiment1_4FM$X...Features,experiment1_4FM$CrossC,col="lightcoral",pch=16) 
points(experiment1_4FM$X...Features,experiment1_4FM$OC,col="thistle4",pch=17) 
lines(experiment1_4FM$X...Features,experiment1_4FM$WD,col="lightblue3",lty="twodash") 
lines(experiment1_4FM$X...Features,experiment1_4FM$CID,col="lightblue4",lty="solid") 
lines(experiment1_4FM$X...Features,experiment1_4FM$CrossC,col="lightcoral",lty="dotted") 
lines(experiment1_4FM$X...Features,experiment1_4FM$OC,col="thistle4",lty="longdash") 
legend("topleft",c("WD", "CID", "Cross*C", "2OC"),lty=c(6,1,3,5), col=c("lightblue3", "lightblue4", "lightcoral",  "thistle4"))

plot(experiment1_5FM$X...Features,experiment1_5FM$WD,log="y",xlab="5 FMs", ylab="Resolution time (sec)",type="p",pch=19,col="lightblue3") 
points(experiment1_5FM$X...Features,experiment1_5FM$CID,col="lightblue4",pch=15) 
points(experiment1_5FM$X...Features,experiment1_5FM$CrossC,col="lightcoral",pch=16) 
points(experiment1_5FM$X...Features,experiment1_5FM$OC,col="thistle4",pch=17) 
lines(experiment1_5FM$X...Features,experiment1_5FM$WD,col="lightblue3",lty="twodash") 
lines(experiment1_5FM$X...Features,experiment1_5FM$CID,col="lightblue4",lty="solid") 
lines(experiment1_5FM$X...Features,experiment1_5FM$CrossC,col="lightcoral",lty="dotted") 
lines(experiment1_5FM$X...Features,experiment1_5FM$OC,col="thistle4",lty="longdash") 
legend("topleft",c("WD", "CID", "Cross*C", "2OC"),lty=c(6,1,3,5), col=c("lightblue3", "lightblue4", "lightcoral",  "thistle4"))
dev.off()