experiment2_2FM = read.csv("./Archivos_graficas/experiment2-2FMs.csv")
experiment2_2FM_resized = experiment2_2FM[,2:5]
max_time_2FM = max(experiment2_2FM_resized)
experiment2_3FM = read.csv("./Archivos_graficas/experiment2-3FMs.csv")
experiment2_3FM_resized = experiment2_3FM[,2:5]
max_time_3FM = max(experiment2_3FM_resized)
experiment2_4FM = read.csv("./Archivos_graficas/experiment2-4FMs.csv")
experiment2_4FM_resized = experiment2_4FM[,2:5]
max_time_4FM = max(experiment2_4FM_resized)
experiment2_5FM = read.csv("./Archivos_graficas/experiment2-5FMs.csv")
experiment2_5FM_resized = experiment2_5FM[,2:5]
max_time_5FM = max(experiment2_5FM_resized)

pdf(file="./Archivos_graficas/experiment2-1.pdf",width=10) 
par(mfrow=c(2,2))
plot(experiment2_2FM$X...Density,experiment2_2FM$WD,ylim=c(0,max_time_2FM),xlab="2 FMs", ylab="Resolution time (sec)",type="p",pch=19,col="lightblue3",cex=1) 
points(experiment2_2FM$X...Density,experiment2_2FM$CID,col="lightblue4",pch=15) 
points(experiment2_2FM$X...Density,experiment2_2FM$CrossC,col="lightcoral",pch=16) 
points(experiment2_2FM$X...Density,experiment2_2FM$OC,col="thistle4",pch=17) 
lines(experiment2_2FM$X...Density,experiment2_2FM$WD,col="lightblue3",lty="twodash") 
lines(experiment2_2FM$X...Density,experiment2_2FM$CID,col="lightblue4",lty="solid") 
lines(experiment2_2FM$X...Density,experiment2_2FM$CrossC,col="lightcoral",lty="dotted") 
lines(experiment2_2FM$X...Density,experiment2_2FM$OC,col="thistle4",lty="longdash") 
legend("topright",c("WD", "CID", "Cross*C", "2OC"),lty=c(6,1,3,5), col=c("lightblue3", "lightblue4", "lightcoral",  "thistle4"))

plot(experiment2_3FM$X...Density,experiment2_3FM$WD,ylim=c(0,max_time_3FM),xlab="3 FMs", ylab="Resolution time (sec)",type="p",pch=19,col="lightblue3") 
points(experiment2_3FM$X...Density,experiment2_3FM$CID,col="lightblue4",pch=15) 
points(experiment2_3FM$X...Density,experiment2_3FM$CrossC,col="lightcoral",pch=16) 
points(experiment2_3FM$X...Density,experiment2_3FM$OC,col="thistle4",pch=17) 
lines(experiment2_3FM$X...Density,experiment2_3FM$WD,col="lightblue3",lty="twodash") 
lines(experiment2_3FM$X...Density,experiment2_3FM$CID,col="lightblue4",lty="solid") 
lines(experiment2_3FM$X...Density,experiment2_3FM$CrossC,col="lightcoral",lty="dotted") 
lines(experiment2_3FM$X...Density,experiment2_3FM$OC,col="thistle4",lty="longdash") 
legend("topright",c("WD", "CID", "Cross*C", "2OC"),lty=c(6,1,3,5), col=c("lightblue3", "lightblue4", "lightcoral",  "thistle4"))

plot(experiment2_4FM$X...Density,experiment2_4FM$WD,ylim=c(0,max_time_4FM),xlab="4 FMs", ylab="Resolution time (sec)",type="p",pch=19,col="lightblue3") 
points(experiment2_4FM$X...Density,experiment2_4FM$CID,col="lightblue4",pch=15) 
points(experiment2_4FM$X...Density,experiment2_4FM$CrossC,col="lightcoral",pch=16) 
points(experiment2_4FM$X...Density,experiment2_4FM$OC,col="thistle4",pch=17) 
lines(experiment2_4FM$X...Density,experiment2_4FM$WD,col="lightblue3",lty="twodash") 
lines(experiment2_4FM$X...Density,experiment2_4FM$CID,col="lightblue4",lty="solid") 
lines(experiment2_4FM$X...Density,experiment2_4FM$CrossC,col="lightcoral",lty="dotted") 
lines(experiment2_4FM$X...Density,experiment2_4FM$OC,col="thistle4",lty="longdash") 
legend("topright",c("WD", "CID", "Cross*C", "2OC"),lty=c(6,1,3,5), col=c("lightblue3", "lightblue4", "lightcoral",  "thistle4"))

plot(experiment2_5FM$X...Density,experiment2_5FM$WD,ylim=c(0,max_time_5FM),xlab="5 FMs", ylab="Resolution time (sec)",type="p",pch=19,col="lightblue3") 
points(experiment2_5FM$X...Density,experiment2_5FM$CID,col="lightblue4",pch=15) 
points(experiment2_5FM$X...Density,experiment2_5FM$CrossC,col="lightcoral",pch=16) 
points(experiment2_5FM$X...Density,experiment2_5FM$OC,col="thistle4",pch=17) 
lines(experiment2_5FM$X...Density,experiment2_5FM$WD,col="lightblue3",lty="twodash") 
lines(experiment2_5FM$X...Density,experiment2_5FM$CID,col="lightblue4",lty="solid") 
lines(experiment2_5FM$X...Density,experiment2_5FM$CrossC,col="lightcoral",lty="dotted") 
lines(experiment2_5FM$X...Density,experiment2_5FM$OC,col="thistle4",lty="longdash") 
legend("topright",c("WD", "CID", "Cross*C", "2OC"),lty=c(6,1,3,5), col=c("lightblue3", "lightblue4", "lightcoral",  "thistle4"))
dev.off()